
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.geom.RoundRectangle2D;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reeve
 */
public class findacc extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    Statement St;
    ResultSet Rs;
    public findacc() {
        initComponents();
        connect();
       
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        
    }
    public void connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ararresto","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(findacc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(findacc.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        softedges2 = new softedges();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        button1 = new Button();
        button2 = new Button();
        jLabel4 = new javax.swing.JLabel();
        findusername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(100, 92, 187));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        softedges2.setBackground(new java.awt.Color(160, 132, 220));
        softedges2.setRoundBottomLeft(50);
        softedges2.setRoundBottomRight(50);
        softedges2.setRoundTopLeft(50);
        softedges2.setRoundTopRight(50);
        softedges2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        softedges2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 480, 16));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Find your account");
        softedges2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 60));
        softedges2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 480, 10));

        button1.setBackground(new java.awt.Color(102, 255, 102));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Search");
        button1.setEffectColor(new java.awt.Color(51, 255, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        softedges2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 80, 40));

        button2.setBackground(new java.awt.Color(255, 51, 102));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Cancel");
        button2.setEffectColor(new java.awt.Color(255, 0, 0));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        softedges2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please enter your usernamer to search for your account.");
        softedges2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 450, 40));

        findusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        findusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findusernameActionPerformed(evt);
            }
        });
        softedges2.add(findusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 390, 40));

        jPanel1.add(softedges2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 480, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(592, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.show();
        dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void findusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findusernameActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String username = findusername.getText();
        forgot forgotpass = new forgot();
        try{          
            java.sql.Statement st= con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("select question from createacc where username = '"+username+"'");
            if (rs.next()){
                forgotpass.forgotquestion.setText(rs.getString(1));
                forgotpass.username.setText(findusername.getText());
                forgotpass.show();
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Please input the correct USERNAME");
            }
            con.close();
            rs.close();
        }
        catch(Exception e){
    }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(findacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(findacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(findacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(findacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new findacc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button button1;
    private Button button2;
    public javax.swing.JTextField findusername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private softedges softedges2;
    // End of variables declaration//GEN-END:variables
}
