
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;


import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reeve
 */
public class forgot extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    Statement St;
    ResultSet Rs;
    public forgot() {
        initComponents();
        cursor();
        connect();
        setGlasspaness();
        centermess();
        
       
        
       
        
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        
    }
    public void cursor (){
        
        Cursor mouse = new Cursor (Cursor.HAND_CURSOR);
        x.setCursor(mouse);  
        back.setCursor(mouse);
       
    }
    public void connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ararresto","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
//    public void glasspane (){
//        messpanel mess = new messpanel();      
//        forgotmess.setSize(320,260);
//        forgotmess.setLocationRelativeTo(null);
//        jPanel1.setOpaque(false);
//        forgotmess.setVisible(true);
//        
//        
////        setBackground(new Color(0,0,0,125));
//        setContentPane(jPanel1);               
//    }
    public void setGlasspaness(){
       getRootPane().setGlassPane(new JComponent(){
       public void paintComponent(Graphics g){
           g.setColor(new Color (0,0,0,150));
           g.fillRect(0,0,getWidth(),getHeight());
           super.paintComponent(g);
           
           
       }
       });
   }
    public void centermess(){
        
        forgotmess.setLocationRelativeTo(null);
        forgotmess.setSize(330,270);
        
        forgotmess.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        forgotmess.setLocation(dim.width/2-forgotmess.getSize().width/2, dim.height/2-forgotmess.getSize().height/2);
        forgotmess.setShape(new RoundRectangle2D.Double(0, 0, forgotmess.getWidth(), forgotmess.getHeight(), 50, 50));
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotmess = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        confirm = new Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        answer = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        button1 = new Button();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        forgotquestion = new javax.swing.JTextField();
        back = new javax.swing.JLabel();

        forgotmess.setUndecorated(true);
        forgotmess.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(160, 132, 220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com-resize-unscreen.gif"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Your password has been changed successfully");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 40));

        confirm.setBackground(new java.awt.Color(100, 92, 187));
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm");
        confirm.setEffectColor(new java.awt.Color(102, 0, 153));
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel2.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 40));

        javax.swing.GroupLayout forgotmessLayout = new javax.swing.GroupLayout(forgotmess.getContentPane());
        forgotmess.getContentPane().setLayout(forgotmessLayout);
        forgotmessLayout.setHorizontalGroup(
            forgotmessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        forgotmessLayout.setVerticalGroup(
            forgotmessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 491));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(100, 92, 187));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Forgot Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newlg.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 270, 10));

        answer.setBackground(new java.awt.Color(100, 92, 187));
        answer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        answer.setForeground(new java.awt.Color(204, 204, 204));
        answer.setText("Enter Answer");
        answer.setBorder(null);
        answer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                answerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                answerFocusLost(evt);
            }
        });
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 260, 40));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 270, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto images/passlock.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto images/sq.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto images/sa.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        x.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        x.setForeground(new java.awt.Color(51, 51, 51));
        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
        });
        jPanel1.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 30));

        password.setBackground(new java.awt.Color(100, 92, 187));
        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("Enter New Password");
        password.setBorder(null);
        password.setEchoChar('\u0000');
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 270, 40));

        button1.setBackground(new java.awt.Color(160, 132, 220));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Save");
        button1.setEffectColor(new java.awt.Color(153, 51, 255));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, 40));

        jLabel3.setFont(new java.awt.Font("MingLiU-ExtB", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Arar Resto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 250, -1));

        forgotquestion.setEditable(false);
        forgotquestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(forgotquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 270, 40));

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<<BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(397, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
       
        String user = username.getText();
        String newpassword = password.getText();
        String ans = answer.getText();
        findacc facc = new findacc();
        createaccount caccount = new createaccount();
        
        
        try {          
            java.sql.Statement st= con.createStatement();
       
            Rs = st.executeQuery("SELECT * FROM createacc where username= '"+user+"' AND answer= '"+ans+"'");
            
            if (Rs.next()){                           
                st.executeUpdate("update createacc set password='"+newpassword+"' where username='"+user+"' and answer='"+ans+"'"); 
                
               
                
                
                password.setText("Enter New Password");
                answer.setText("Enter Answer");
                password.setEchoChar('\u0000');
                password.setForeground(new Color(204, 204, 204));
                answer.setForeground(new Color(204, 204, 204));
                getRootPane().getGlassPane().setVisible(true);
                forgotmess.setVisible(true);
                     
                getRootPane().getGlassPane().setVisible(true);
                                               
            }
           
            else {
                JOptionPane.showMessageDialog(null, "Please input correct ANSWER");
            }
        }catch (SQLException ex) {
            Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_button1ActionPerformed

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if (password.getText().equals("")){
            password.setText("Enter New Password");
            password.setForeground(new Color (204,204,204));
            password.setEchoChar('\u0000');

        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if (password.getText().equals("Enter New Password")){
            password.setText("");
            password.setForeground(new Color(0,0,0));
            password.setEchoChar('*');

        }
    }//GEN-LAST:event_passwordFocusGained

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        // TODO add your handling code here:
        int dialogresult = JOptionPane.showConfirmDialog(null, "Do you want to EXIT?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogresult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_xMouseClicked

    private void answerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answerFocusLost
        // TODO add your handling code here:
        if (answer.getText().equals("")){
            answer.setText("Enter Answer");
            answer.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_answerFocusLost

    private void answerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answerFocusGained
        // TODO add your handling code here:
        if (answer.getText().equals("Enter Answer")){
            answer.setText("");
            answer.setForeground(new Color(0,0,0));

        }
    }//GEN-LAST:event_answerFocusGained

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        findacc findaccount = new findacc();
        findaccount.show();
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        getRootPane().getGlassPane().setVisible(false);
        forgotmess.setVisible(false   );
       
        
       
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JLabel back;
    private Button button1;
    private Button confirm;
    private javax.swing.JDialog forgotmess;
    public javax.swing.JTextField forgotquestion;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPasswordField password;
    public javax.swing.JLabel username;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
